### ISSUE TITLE
Broken inspector fields

### ISSUE THREAD

**Issue by Muciojad** [alelievr/NodeGraphProcessor#101]
Hey, today I started playing around with your awesome node editor. I really need solution that supports exposing inspector fields in nodes (like NodeGraphProcessor), and I encountered a issue trying to use InspectorNode included with forked project.
Issue is both in 2019.3.15f1 and 2020.1.4f.

InspectorNode looks like [that](https://imgur.com/a/awCSsn1)

The only things I did after downloading forked project were:
1. opening project in Unity (2020 then 2019)
2. opening "Window/01 DefaultGraph)
3. adding inspector node from context menu

Each time I move the node, a weird line under node appears ( I ended with 8 lines).
Also created my own node based on BaseNode with public field marked with [ShowInInspector] attribute -> result is just the same.

There is no error in console after opening forked project (opened at master branch).

Hope you can help me figure out how to repair it, have a good day!

**Comment by alelievr** [comment]
Hello, Thanks for reporting the issue :)
I pushed the fix in master: a1be720961c7d3427d8ef1e18548836038f177c3 (somehow the drawer code wasn't working correctly with the inspector)

**Comment by Muciojad** [comment]
Thanks for resolving it so quickly! Great job!

**Comment by Muciojad** [comment]
Hey, sorry for bothering you again - I just pulled changed from your repo, although rendering artefacts are gone, I still can't see inspector fields. Shoul I open new issue for that?

FYI this is still InspectorNode from examples folder, I just changed styling and make node bigger to see if maybe these fields are hidden somewhere.
![image](https://user-images.githubusercontent.com/10184394/94670093-62fd6380-0312-11eb-9ecf-6c91ce15c13e.png)
